# Generated by Django 5.2.13 on 2026-05-01 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name="Lavozim nomi (O'z)")),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Lavozim nomi (Ru)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_uz', models.CharField(max_length=200, verbose_name="F.I.Sh. (O'z)")),
                ('full_name_ru', models.CharField(blank=True, max_length=200, verbose_name='F.I.Sh. (Ru)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='leaders/', verbose_name='Rasm')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta')),
                ('reception_days_uz', models.CharField(blank=True, max_length=255, verbose_name="Qabul kunlari (O'z)")),
                ('reception_days_ru', models.CharField(blank=True, max_length=255, verbose_name='Qabul kunlari (Ru)')),
                ('biography_uz', models.TextField(blank=True, verbose_name="Biografiya (O'z)")),
                ('biography_ru', models.TextField(blank=True, verbose_name='Biografiya (Ru)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadership.position', verbose_name='Lavozimi')),
            ],
            options={
                'verbose_name': 'Rahbar',
                'verbose_name_plural': 'Rahbariyat',
                'ordering': ['order', 'position__order'],
            },
        ),
    ]
