# Generated by Django 5.2.13 on 2026-05-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='biography_kr',
            field=models.TextField(blank=True, verbose_name='Biografiya (Kr)'),
        ),
        migrations.AddField(
            model_name='leader',
            name='full_name_kr',
            field=models.CharField(blank=True, max_length=200, verbose_name='F.I.Sh. (Kr)'),
        ),
        migrations.AddField(
            model_name='leader',
            name='reception_days_kr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Qabul kunlari (Kr)'),
        ),
        migrations.AddField(
            model_name='position',
            name='name_kr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozim nomi (Kr)'),
        ),
    ]
