# Generated by Django 5.2.13 on 2026-05-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh.')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta')),
                ('subject', models.CharField(max_length=255, verbose_name='Murojaat mavzusi')),
                ('message', models.TextField(verbose_name='Murojaat matni')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', "Ko'rib chiqilmoqda"), ('resolved', 'Hal etildi'), ('rejected', 'Rad etildi')], default='new', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
