# Generated by Django 5.2.13 on 2026-05-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='region',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hudud (tuman/shahar)'),
        ),
    ]
