# Generated by Django 5.2.13 on 2026-05-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255, verbose_name="Bo'lim/Boshqarma nomi (O'z)")),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name="Bo'lim/Boshqarma nomi (Ru)")),
                ('description_uz', models.TextField(blank=True, verbose_name="Tavsifi (O'z)")),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsifi (Ru)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': "Tuzilma bo'limi",
                'verbose_name_plural': 'Tashkiliy tuzilma',
                'ordering': ['order'],
            },
        ),
    ]
