# Generated by Django 5.2.13 on 2026-05-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description_kr',
            field=models.TextField(blank=True, verbose_name='Tavsifi (Kr)'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_name_kr',
            field=models.CharField(blank=True, max_length=200, verbose_name="Bo'lim boshlig'i (Kr)"),
        ),
        migrations.AddField(
            model_name='department',
            name='head_name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name="Bo'lim boshlig'i (Ru)"),
        ),
        migrations.AddField(
            model_name='department',
            name='head_name_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name="Bo'lim boshlig'i (O'z)"),
        ),
        migrations.AddField(
            model_name='department',
            name='name_kr',
            field=models.CharField(blank=True, max_length=255, verbose_name="Bo'lim/Boshqarma nomi (Kr)"),
        ),
    ]
