# Generated by Django 5.2.13 on 2026-05-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255, verbose_name="Tashkilot nomi (O'z)")),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Tashkilot nomi (Ru)')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqami')),
                ('hotline', models.CharField(blank=True, max_length=50, verbose_name='Ishonch telefoni')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta')),
                ('work_hours', models.CharField(blank=True, max_length=255, verbose_name='Ish vaqti')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram havolasi')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook havolasi')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram havolasi')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube havolasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Umumiy ma'lumot",
                'verbose_name_plural': "Umumiy ma'lumotlar",
            },
        ),
    ]
