# Generated by Django 5.2.13 on 2026-05-03 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name="Sarlavha (O'z)")),
                ('title_kr', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Kr)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('subtitle_uz', models.CharField(blank=True, max_length=255, verbose_name="Qo'shimcha sarlavha (O'z)")),
                ('subtitle_kr', models.CharField(blank=True, max_length=255, verbose_name="Qo'shimcha sarlavha (Kr)")),
                ('subtitle_ru', models.CharField(blank=True, max_length=255, verbose_name="Qo'shimcha sarlavha (Ru)")),
                ('description_uz', models.TextField(blank=True, verbose_name="Tavsif (O'z)")),
                ('description_kr', models.TextField(blank=True, verbose_name='Tavsif (Kr)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (Ru)')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Rasm')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Bosh sahifa banneri',
                'verbose_name_plural': 'Bosh sahifa bannerlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Faqat lotin harflari, raqamlar va '-' belgisi. Masalan: xizmatlar, bolalar-salomatligi", max_length=100, unique=True, verbose_name='URL manzil (slug)')),
                ('title_uz', models.CharField(max_length=255, verbose_name="Sarlavha (O'z)")),
                ('title_kr', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Kr)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('meta_description_uz', models.CharField(blank=True, help_text="Qidiruv tizimlarida ko'rinadigan qisqa tavsif (150–160 belgi)", max_length=300, verbose_name="Meta tavsif (O'z)")),
                ('show_in_nav', models.BooleanField(default=False, help_text="Belgilansa, bu sahifa yuqori navigatsiya menyusida avtomatik paydo bo'ladi", verbose_name="Asosiy menyuga qo'shish")),
                ('nav_order', models.PositiveIntegerField(default=99, help_text="Menyudagi o'rni (kichik son = oldinda)", verbose_name='Menyu tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name="Faol (saytda ko'rinadi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maxsus sahifa',
                'verbose_name_plural': 'Maxsus sahifalar',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('quick', 'Tezkor havolalar'), ('gov', 'Davlat saytlari')], default='quick', max_length=10, verbose_name="Bo'lim")),
                ('label_uz', models.CharField(max_length=100, verbose_name="Nomi (O'z)")),
                ('label_kr', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Kr)')),
                ('label_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ru)')),
                ('url', models.CharField(max_length=255, verbose_name='Havola')),
                ('is_external', models.BooleanField(default=False, verbose_name='Tashqi havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Pastki menyu havolasi',
                'verbose_name_plural': 'Pastki menyu havolalari',
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('location', models.CharField(choices=[('hero', 'Bosh sahifa fon rasmi'), ('about', 'Biz haqimizda rasm'), ('contact', 'Aloqa sahifasi rasmi'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Joylashuvi')),
                ('image', models.ImageField(upload_to='assets/', verbose_name='Rasm')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt matn')),
            ],
            options={
                'verbose_name': 'Sayt rasmi',
                'verbose_name_plural': 'Sayt rasmlari',
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_uz', models.CharField(max_length=100, verbose_name="Nomi (O'z)")),
                ('label_kr', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Kr)')),
                ('label_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ru)')),
                ('url', models.CharField(max_length=255, verbose_name='Havola (masalan: /about)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Yuqori menyu havolasi',
                'verbose_name_plural': 'Yuqori menyu havolalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default='home', max_length=50, verbose_name='Sahifa (masalan: home)')),
                ('section_type', models.CharField(choices=[('text', 'Matn bloki'), ('cards', 'Kartochkalar'), ('stats', 'Statistika'), ('cta', 'Chaqiruv (CTA)')], default='text', max_length=20, verbose_name="Bo'lim turi")),
                ('title_uz', models.CharField(max_length=255, verbose_name="Sarlavha (O'z)")),
                ('title_kr', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Kr)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('content_uz', models.TextField(blank=True, verbose_name="Matn (O'z)")),
                ('content_kr', models.TextField(blank=True, verbose_name='Matn (Kr)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='Rasm')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumot (JSON)")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Sahifa bo'limi",
                'verbose_name_plural': "Sahifa bo'limlari",
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0ea5e9', max_length=7, verbose_name='Asosiy rang (primary)')),
                ('secondary_color', models.CharField(default='#14b8a6', max_length=7, verbose_name='Ikkinchi rang (secondary)')),
                ('accent_color', models.CharField(default='#f59e0b', max_length=7, verbose_name='Aksent rang')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Sayt logotipi')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='generalinfo',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='about_kr',
            field=models.TextField(blank=True, verbose_name='Boshqarma haqida (Kr)'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='about_ru',
            field=models.TextField(blank=True, verbose_name='Boshqarma haqida (Ru)'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='about_uz',
            field=models.TextField(blank=True, verbose_name="Boshqarma haqida (O'z)"),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='address_kr',
            field=models.TextField(blank=True, verbose_name='Manzil (Kr)'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='address_ru',
            field=models.TextField(blank=True, verbose_name='Manzil (Ru)'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='address_uz',
            field=models.TextField(default='', verbose_name="Manzil (O'z)"),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='history_kr',
            field=models.TextField(blank=True, verbose_name='Boshqarma tarixi (Kr)'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='history_ru',
            field=models.TextField(blank=True, verbose_name='Boshqarma tarixi (Ru)'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='history_uz',
            field=models.TextField(blank=True, verbose_name="Boshqarma tarixi (O'z)"),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='name_kr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tashkilot nomi (Kr)'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='statute_link',
            field=models.URLField(blank=True, verbose_name='Nizom havolasi (URL)'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='work_hours_kr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ish vaqti (Kr)'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='work_hours_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ish vaqti (Ru)'),
        ),
        migrations.AddField(
            model_name='generalinfo',
            name='work_hours_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name="Ish vaqti (O'z)"),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.CreateModel(
            name='CustomPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Matn bloki'), ('image_text', 'Rasm + Matn'), ('cards', 'Kartochkalar'), ('cta', 'Chaqiruv tugmasi (CTA)'), ('divider', "Bo'luvchi chiziq")], default='text', max_length=20, verbose_name='Blok turi')),
                ('title_uz', models.CharField(blank=True, max_length=255, verbose_name="Sarlavha (O'z)")),
                ('title_kr', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Kr)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('content_uz', models.TextField(blank=True, help_text='HTML teglarini ishlatish mumkin: &lt;b&gt;, &lt;i&gt;, &lt;br&gt;, &lt;ul&gt;&lt;li&gt;...', verbose_name="Matn (O'z)")),
                ('content_kr', models.TextField(blank=True, verbose_name='Matn (Kr)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('image', models.ImageField(blank=True, help_text="'Rasm + Matn' bloki uchun. Tavsiya: 800×500 px", null=True, upload_to='pages/', verbose_name='Rasm')),
                ('image_position', models.CharField(choices=[('right', "O'ngda"), ('left', 'Chapda')], default='right', help_text="'Rasm + Matn' blokida rasm matnning qaysi tomonida turadi", max_length=10, verbose_name='Rasm joylashuvi')),
                ('link_text_uz', models.CharField(blank=True, max_length=100, verbose_name="Tugma matni (O'z)")),
                ('link_text_kr', models.CharField(blank=True, max_length=100, verbose_name='Tugma matni (Kr)')),
                ('link_text_ru', models.CharField(blank=True, max_length=100, verbose_name='Tugma matni (Ru)')),
                ('link_url', models.CharField(blank=True, help_text='Masalan: /contact  yoki  https://gov.uz', max_length=255, verbose_name='Tugma havolasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.custompage', verbose_name='Sahifa')),
            ],
            options={
                'verbose_name': 'Sahifa bloki',
                'verbose_name_plural': 'Sahifa bloklari',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CustomPageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name="Sarlavha (O'z)")),
                ('title_kr', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Kr)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('text_uz', models.TextField(blank=True, verbose_name="Matn (O'z)")),
                ('text_kr', models.TextField(blank=True, verbose_name='Matn (Kr)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('icon', models.CharField(blank=True, help_text='Emoji (masalan: 🏥) yoki fon-awesome klass (fa-heart)', max_length=50, verbose_name='Ikonka')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/cards/', verbose_name='Rasm')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.custompageblock', verbose_name='Blok')),
            ],
            options={
                'verbose_name': 'Kartochka',
                'verbose_name_plural': 'Kartochkalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name="Sarlavha (O'z)")),
                ('title_kr', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Kr)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('text_uz', models.TextField(blank=True, verbose_name="Matn (O'z)")),
                ('text_kr', models.TextField(blank=True, verbose_name='Matn (Kr)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikonka nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/', verbose_name='Rasm')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.pagesection', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Kartochka',
                'verbose_name_plural': 'Kartochkalar',
                'ordering': ['order'],
            },
        ),
    ]
