# Generated by Django 5.2.13 on 2026-05-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Kategoriya nomi (O'z)")),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Kategoriya nomi (Ru)')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name="Sarlavha (O'z)")),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Rasm')),
                ('content_uz', models.TextField(verbose_name="Matn (O'z)")),
                ('content_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('published_at', models.DateTimeField(verbose_name='Chop etilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at'],
            },
        ),
    ]
