# Generated by Django 5.2.13 on 2026-05-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_kr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kategoriya nomi (Kr)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_kr',
            field=models.TextField(blank=True, verbose_name='Matn (Kr)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Kr)'),
        ),
    ]
