# Generated by Django 5.2.13 on 2026-05-01 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=100, verbose_name="Kategoriya nomi (O'z)")),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Kategoriya nomi (Ru)')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Hujjat kategoriyasi',
                'verbose_name_plural': 'Hujjat kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name="Sarlavha (O'z)")),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Hujjat raqami')),
                ('date', models.DateField(verbose_name='Qabul qilingan sana')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fayl')),
                ('link', models.URLField(blank=True, verbose_name='Tashqi havola')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['-date'],
            },
        ),
    ]
