# Generated by Django 5.2.13 on 2026-05-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI (GPT-4o, GPT-4o-mini...)'), ('gemini', 'Google Gemini (gemini-1.5-flash...)'), ('openrouter', "OpenRouter (ko'plab modellar)"), ('groq', 'Groq (Llama, Mixtral...)')], default='openai', help_text='Qaysi AI xizmatidan foydalanishni tanlang', max_length=20, verbose_name='AI xizmat provayderi')),
                ('api_key', models.CharField(help_text='Tanlangan provayder saytidan olingan maxfiy kalit', max_length=500, verbose_name='API kalit (API Key)')),
                ('model_name', models.CharField(default='gpt-4o-mini', help_text='OpenAI: gpt-4o-mini, gpt-4o | Gemini: gemini-1.5-flash, gemini-1.5-pro | OpenRouter: mistralai/mistral-7b-instruct | Groq: llama3-8b-8192', max_length=100, verbose_name='Model nomi')),
                ('system_prompt', models.TextField(default="Siz sayt foydalanuvchilariga yordam beruvchi AI yordamchisiz. Samarali, qisqa va aniq javoblar bering. Faqat quyidagi ma'lumotlar asosida javob bering.", help_text="AI yordamchining xulq-atvori va yo'riqnomasi. Masalan: qaysi tashkilot haqida, qanday murojaat qilish mumkin, qaysi xizmatlar bor.", verbose_name='Tizim xabari (System Prompt)')),
                ('temperature', models.FloatField(default=0.7, help_text='0.0 = aniq/qattiq, 1.0 = ijodiy/erkin', verbose_name='Ijodkorlik darajasi (0.0 – 1.0)')),
                ('max_tokens', models.PositiveIntegerField(default=800, help_text="1 token ≈ 4 harif. 800 token ≈ 600 so'z", verbose_name='Maksimal javob uzunligi (tokenlar)')),
                ('is_active', models.BooleanField(default=True, help_text="Belgilansa, saytda chat tugmasi paydo bo'ladi", verbose_name="Faol (saytda ko'rinadi)")),
                ('welcome_message_uz', models.CharField(default='Salom! Men sayt yordamchisiman. Qanday yordam bera olaman?', max_length=300, verbose_name="Salomlashuv xabari (O'z)")),
                ('welcome_message_ru', models.CharField(blank=True, default='Здравствуйте! Я помощник сайта. Чем могу помочь?', max_length=300, verbose_name='Salomlashuv xabari (Ru)')),
                ('welcome_message_kr', models.CharField(blank=True, default='Салом! Мен сайт ёрдамчисиман. Қандай ёрдам бера оламан?', max_length=300, verbose_name='Salomlashuv xabari (Kr)')),
            ],
            options={
                'verbose_name': 'AI Yordamchi sozlamalari',
                'verbose_name_plural': 'AI Yordamchi sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', "Umumiy ma'lumot"), ('services', 'Xizmatlar'), ('contacts', "Aloqa ma'lumotlari"), ('faq', "Ko'p so'raladigan savollar"), ('procedure', 'Qabul tartibi / Murojaat'), ('other', 'Boshqa')], default='general', max_length=20, verbose_name='Kategoriya')),
                ('title', models.CharField(help_text='Masalan: Qabul vaqti, Manzil, Bolalar shifokoriga murojaat', max_length=255, verbose_name='Mavzu / Sarlavha')),
                ('content', models.TextField(help_text="AI shu ma'lumotga tayangan holda javob beradi. Aniq va to'liq yozing. Tilni aralashtirishingiz mumkin.", verbose_name="Ma'lumot matni")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Bilimlar bazasi yozuvi',
                'verbose_name_plural': 'Bilimlar bazasi',
                'ordering': ['category', 'order'],
            },
        ),
    ]
